### ISSUE TITLE
 FATAL  api[resource].map is not a function 

### ISSUE THREAD

**Issue by LeCoupa** [galvez/yamlful#5]
* Install the latest version of the package (0.4.2) with `npm install yamlful-nuxt`

* Add the package to the loaded modules.

```
 modules: [
    "yamlful-nuxt"
]
```

* Run nuxt with npm run dev. The following error happens:

> FATAL  api[resource].map is not a function

**Comment by galvez** [comment]
@LeCoupa thanks for submitting this, I'm taking a look now.

**Comment by galvez** [comment]
@LeCoupa I see what's happening. That's a YAML parsing error.

I get the same error with an empty `api.yml` file. If I add:

```
sample:
  - method: get
    get: /resource/:id/subresource/:subId
```

In my `api.yml`, then it works.

But I just realized I should probably change it to require specifying a YAML folder too, otherwise it might fail if there are other YAML files in your source directory.

Will push a new release with this fix shortly.

**Comment by LeCoupa** [comment]
Excellent, thank you for the quick fix.
